name: proto-3
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.2=pyh0d26453_1
  - python=3.14.0=h1858270_101_cp314
  - python_abi=3.14=1_cp314
  - readline=8.3=h0b18652_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - blake3==1.0.8
      - contourpy==1.3.3
      - customtkinter==5.2.2
      - cycler==0.12.1
      - darkdetect==0.8.0
      - fonttools==4.60.1
      - kiwisolver==1.4.9
      - magiccube==1.2.0
      - matplotlib==3.10.7
      - numpy==2.3.5
      - packaging==25.0
      - pillow==12.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - rubik-cube==0.0.2
      - six==1.17.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/proto-3
